### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
A couple of minor improvements.

### CODE REVIEW

**Comment by janko-m** [comment]
Thanks for the patches, but I'm not sure about the motivation behind them. The reason why I didn't set Rake as development dependency is that prefixing commands with `bundle exec` is for me around 3 times slower than running it normally and having `require "bundler/setup"`. But if Rake is set in the Gemfile and you don't prefix `rake` command with `bundle exec`, you would get version mismatches which can only be solved by updating Rake, which is a bit annoying to do every time you update the Rake gem locally outside of the Shrine project.

About the second change, it's arguably longer and more complex than the current code, can the current fail in some way? If not, I would prefer the simplicity.

**Comment by deivid-rodriguez** [comment]
> But if Rake is set in the Gemfile and you don't prefix rake command with bundle exec, you would get version mismatches which can only be solved by updating Rake, which is a bit annoying to do every time you update the Rake gem locally outside of the Shrine project.

Wouldn't that happen with the other dependencies too if you don't use `bundler`? I added this because I'm used to prefix commands with `bundle exec` and I was getting errors when doing it with `rake`.

Regarding the second change, I'm not sure whether it could fail or not but I've seen this used in libraries where compatibility across different platforms is important (rubygems), and since I chose to do it this way in my own `pretty_location` method, I thought of proposing it here too.

**Comment by janko-m** [comment]
Aha, I understand the `File.join` change now, because on Windows the separator is "\". The problem is that this change would on Windows generate "foo\bar\baz" for S3 as well, which is an invalid object key. I would accept a solution on FileSystem storage directly, which would replace all "/" with "\".

You're right about the Rake dependency, I cherry picked your commit.

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request closed without merging**
