### PR TITLE
use aws-sdk gem version 3 modularity

### PR DESCRIPTION
**Pull request by lizdeika**

### CODE REVIEW

**Comment by janko-m** [comment]
Thanks for the patch!

While running the tests on aws-sdk-s3, I discovered a regression which breaks `Storage::S3::Client#open` – https://github.com/aws/aws-sdk-ruby/issues/1588. Let's wait a bit and see whether this will be fixed soon.

**Comment by dsexton** [comment]
@janko-m was this fixed in aws-sdk-s3 1.1.0?

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/CHANGELOG.md#110-2017-09-01

**Comment by janko-m** [comment]
@dsexton Yes, it has! I somehow missed that release. I will test and merge shortly.

**Comment by janko-m** [comment]
@dsexton It seems that, while that fix brought back streaming for `Aws::S3::Client#get_object`, it did not bring it for `Aws::S3::Object#get`, which Shrine is using. https://github.com/janko-m/shrine/blob/edc627a87923d8d38842c480bca6805339be936f/lib/shrine/storage/s3.rb#L241-L246

Theoretically I could work around that in Shrine, but it would make the code more verbose, and I would like to avoid that unless it's absolutely necessary. I've let the aws-sdk-ruby maintainers know, so hopefully they'll fix it and prep up another release soon.

**Comment by bodrovis** [comment]
@janko-m could you release a new version that has this feature please? :)

**Comment by janko-m** [comment]
@bodrovis I'm preparing a release, it should be done today or tomorrow.

**Comment by janko-m** [comment]
@bodrovis Shrine 2.7.0 has just been [released](http://shrinerb.com/rdoc/files/doc/release_notes/2_7_0_md.html).

**Comment by bodrovis** [comment]
@janko-m Thank you so much. By the way, yet another article about Shrine is out: https://scotch.io/tutorials/asynchronous-chat-with-rails-and-actioncable and part 2 is coming soon!

**Pull request merged**
